import axios from 'axios';
export const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8080/api', headers: { 'Content-Type': 'application/json' } });
api.interceptors.request.use(config => { const token=localStorage.getItem('sponsor_match_auth'); if(token) config.headers.Authorization=`Bearer ${JSON.parse(token).token}`; return config; });
api.interceptors.response.use(r=>r,e=>{if([401,403].includes(e.response?.status)){localStorage.removeItem('sponsor_match_auth');if(!location.pathname.match(/^\/(login|register)$/))location.assign('/login')}return Promise.reject(e)});
export const authApi={login:d=>api.post('/auth/login',d),register:d=>api.post('/auth/register',d)};
export const campaignApi={mine:()=>api.get('/campaigns/my'),get:id=>api.get(`/campaigns/${id}`),create:d=>api.post('/campaigns',d),update:(id,d)=>api.put(`/campaigns/${id}`,d),remove:id=>api.delete(`/campaigns/${id}`)};
export const creatorApi={mine:()=>api.get('/creators/profile'),getProfile:()=>api.get('/creators/profile'),createProfile:d=>api.post('/creators/profile',d),updateProfile:d=>api.put('/creators/profile',d),get:id=>api.get(`/creators/${id}`),search:params=>api.get('/creators/search',{params}),save:(d,exists)=>exists?api.put('/creators/profile',d):api.post('/creators/profile',d)};
export const matchApi=id=>api.get(`/matching/campaign/${id}`); export const shortlistApi={list:()=>api.get('/shortlists'),add:d=>api.post('/shortlists',d),remove:id=>api.delete(`/shortlists/${id}`)}; export const collaborationApi={sent:()=>api.get('/collaboration-requests/sent'),received:()=>api.get('/collaboration-requests/received'),send:d=>api.post('/collaboration-requests',d),decide:(id,a)=>api.patch(`/collaboration-requests/${id}/${a}`)}; export const notificationApi={list:()=>api.get('/notifications'),read:id=>api.patch(`/notifications/${id}/read`)};
export const messageApi={listConversations:()=>api.get('/messages/conversations'),getMessages:id=>api.get(`/messages/conversations/${id}`),initiate:d=>api.post('/messages',d),send:(id,d)=>api.post(`/messages/conversations/${id}`,d)};
