package com.sponsormatch.service;
import com.sponsormatch.dto.CreatorDtos.*; import com.sponsormatch.entity.*; import com.sponsormatch.exception.ApiException; import com.sponsormatch.repository.*; import lombok.RequiredArgsConstructor; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.util.*;
@Service @RequiredArgsConstructor public class CreatorService { private final CreatorProfileRepository profiles; private final UserRepository users;
 public CreatorResponse create(Long uid,ProfileRequest r){User u=creator(uid); if(profiles.findByUserId(uid).isPresent())throw new ApiException(HttpStatus.CONFLICT,"Creator profile already exists"); return map(profiles.save(apply(CreatorProfile.builder().user(u).build(),r)));} public CreatorResponse update(Long uid,ProfileRequest r){return map(profiles.save(apply(profiles.findByUserId(uid).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Creator profile not found")),r)));} public CreatorResponse mine(Long uid){return map(profiles.findByUserId(uid).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Creator profile not found")));} public CreatorResponse byId(Long id){return map(profiles.findById(id).or(()->profiles.findByUserId(id)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Creator profile not found")));}
 public List<CreatorResponse> search(String q,String category,String platform,String location,Long min,Long max,BigDecimal engagement,BigDecimal minPrice,BigDecimal maxPrice){return profiles.findAll().stream().filter(p->matchesQ(q,p)&&eq(category,p.getCategory())&&eq(platform,p.getPlatform())&&contains(location,p.getLocation())&&(min==null||nz(p.getFollowers())>=min)&&(max==null||nz(p.getFollowers())<=max)&&(engagement==null||val(p.getEngagementRate()).compareTo(engagement)>=0)&&(minPrice==null||(p.getPriceMax()!=null&&p.getPriceMax().compareTo(minPrice)>=0))&&(maxPrice==null||(p.getPriceMin()!=null&&p.getPriceMin().compareTo(maxPrice)<=0))).map(this::map).toList();}
 public List<CreatorResponse> search(String category,String platform,String location,Long min,Long max,BigDecimal engagement){return search(null,category,platform,location,min,max,engagement,null,null);}
 private boolean matchesQ(String q,CreatorProfile p){if(q==null||q.isBlank())return true;String s=q.toLowerCase();return (p.getUser()!=null&&p.getUser().getName()!=null&&p.getUser().getName().toLowerCase().contains(s))||(p.getBio()!=null&&p.getBio().toLowerCase().contains(s))||(p.getCategory()!=null&&p.getCategory().toLowerCase().contains(s))||(p.getPlatform()!=null&&p.getPlatform().toLowerCase().contains(s))||(p.getLocation()!=null&&p.getLocation().toLowerCase().contains(s));}
 private boolean contains(String filter,String value){return filter==null||filter.isBlank()||(value!=null&&value.toLowerCase().contains(filter.trim().toLowerCase()));}
 private CreatorProfile apply(CreatorProfile p,ProfileRequest r){if(r.priceMax().compareTo(r.priceMin())<0)throw new ApiException(HttpStatus.BAD_REQUEST,"priceMax must be greater than or equal to priceMin");p.setBio(r.bio());p.setCategory(r.category().trim());p.setPlatform(r.platform().trim());p.setFollowers(r.followers());p.setEngagementRate(r.engagementRate());p.setLocation(r.location().trim());p.setPriceMin(r.priceMin());p.setPriceMax(r.priceMax());p.setProfileImage(r.profileImage());return p;} private User creator(Long id){User u=users.findById(id).orElseThrow(()->new ApiException(HttpStatus.UNAUTHORIZED,"User not found"));if(u.getRole()!=Role.CREATOR)throw new ApiException(HttpStatus.FORBIDDEN,"Creator role required");return u;} private boolean eq(String filter,String value){return filter==null||filter.isBlank()||(value!=null&&filter.equalsIgnoreCase(value.trim()));} private long nz(Long n){return n==null?0:n;} private BigDecimal val(BigDecimal n){return n==null?BigDecimal.ZERO:n;} public CreatorResponse map(CreatorProfile p){return new CreatorResponse(p.getId(),p.getUser().getName(),p.getBio(),p.getCategory(),p.getPlatform(),p.getFollowers(),p.getEngagementRate(),p.getLocation(),p.getPriceMin(),p.getPriceMax(),p.getProfileImage());}}
